# syntax=docker/dockerfile:1

FROM node:20-alpine AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN echo "Running CI"
RUN npm install --legacy-peer-deps
RUN npm ci --legacy-peer-deps 


FROM node:20-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# ✅ MUST be set BEFORE build

ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

# New Relic Browser Configuration (MUST be set BEFORE build)
ARG NEXT_PUBLIC_NEW_RELIC_BROWSER_ENABLED
ARG NEXT_PUBLIC_NEW_RELIC_ACCOUNT_ID
ARG NEXT_PUBLIC_NEW_RELIC_TRUST_KEY
ARG NEXT_PUBLIC_NEW_RELIC_AGENT_ID
ARG NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY
ARG NEXT_PUBLIC_NEW_RELIC_APPLICATION_ID
ARG NEXT_PUBLIC_ENVIRONMENT

ENV NEXT_PUBLIC_NEW_RELIC_BROWSER_ENABLED=$NEXT_PUBLIC_NEW_RELIC_BROWSER_ENABLED
ENV NEXT_PUBLIC_NEW_RELIC_ACCOUNT_ID=$NEXT_PUBLIC_NEW_RELIC_ACCOUNT_ID
ENV NEXT_PUBLIC_NEW_RELIC_TRUST_KEY=$NEXT_PUBLIC_NEW_RELIC_TRUST_KEY
ENV NEXT_PUBLIC_NEW_RELIC_AGENT_ID=$NEXT_PUBLIC_NEW_RELIC_AGENT_ID
ENV NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY=$NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY
ENV NEXT_PUBLIC_NEW_RELIC_APPLICATION_ID=$NEXT_PUBLIC_NEW_RELIC_APPLICATION_ID
ENV NEXT_PUBLIC_ENVIRONMENT=$NEXT_PUBLIC_ENVIRONMENT

RUN npm run build


FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup -S nextjs && adduser -S nextjs -G nextjs

RUN mkdir -p /app/public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.js ./next.config.js

USER nextjs
EXPOSE 3000

CMD ["npm", "run", "start"]
